/**

 Simple OPML Generator
 
 Just provide list of URLs in file `list.txt`

*/
var fs      = require('fs');
var cheerio = require('cheerio');
var restler = require('restler');

var list = fs.readFileSync('list.txt', 'utf-8').split('\n');
var out  = [];
var todo = list.length;

for (var i=0; i<list.length; i++) {
   restler.get(list[i].trim()).on('complete', function (res) {
      var $   = cheerio.load(res);
      var entry = {
         'url': null,
         'title': null
      };
      entry.url   = $('link[type="application/atom+xml"]').attr('href');
      entry.title = $('title').text().trim();
      out.push(entry);
      todo--;
      if (todo == 0) done(console.log);
   });
}

function done(print) {

print('<?xml version="1.0" encoding="UTF-8"?>');
print('<opml version="1.0">');
print('  <head><title>Generated by OMPLGen</title></head>');
print('  <body><outline text="List">');
for (var i=0; i<out.length; i++) {
   var e = out[i];
   if (!e.title || !e.url) continue;
   e.title = e.title.replace(/"/g, "'").replace(/\n/g, ' ').replace(/&/g, '');
   print('    <outline title="' + e.title  +'" text="' + e.title + '" type="rss" xmlUrl="' + e.url + '" />');
}
print('  </outline></body>');
print('</opml>');
}

